---
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 20
  Exclude:
    - 'spec/*'
    - 'spec/**/*'

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Max: 250

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'departure.gemspec'
    - 'test_database.rb'

Metrics/MethodLength:
  Max: 30

Metrics/ModuleLength:
  Max: 250

Metrics/ParameterLists:
  Max: 5

Performance/Casecmp:
  Enabled: false

Style/BracesAroundHashParameters:
  Exclude:
    - 'spec/fixtures/migrate/**.rb'
    - 'spec/integration/**.rb'

Style/CommandLiteral:
  Exclude:
    - 'test_database.rb'

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Exclude:
    - 'spec/integration_spec.rb'

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/UnneededPercentQ:
  Exclude:
    - 'departure.gemspec'

